name: CI/CD Pipeline

on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: run
        run: echo "helo"

  lint:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: run
        run: echo "helo"

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: run
        run: echo "helo"

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: run
        run: echo "helo"

